# Generated by Django 6.0.1 on 2026-01-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='referral_doctor',
            field=models.ForeignKey(blank=True, help_text='Internal doctor referral', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_visits', to='people.staff'),
        ),
        migrations.AddField(
            model_name='visit',
            name='referral_external',
            field=models.CharField(blank=True, help_text='External doctor/hospital referral', max_length=255, null=True),
        ),
    ]
