# Generated by Django 6.0.1 on 2026-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='doctor_type',
            field=models.CharField(blank=True, choices=[('GENERAL_PHYSICIAN', 'General Physician'), ('CARDIOLOGIST', 'Cardiologist'), ('DERMATOLOGIST', 'Dermatologist'), ('ENT', 'ENT Specialist'), ('NEUROLOGIST', 'Neurologist'), ('GYNECOLOGIST', 'Gynecologist'), ('ORTHOPEDIC', 'Orthopedic Surgeon'), ('PEDIATRICIAN', 'Pediatrician'), ('PSYCHIATRIST', 'Psychiatrist'), ('SURGEON', 'General Surgeon'), ('UROLOGIST', 'Urologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('DENTIST', 'Dentist'), ('ENDOCRINOLOGIST', 'Endocrinologist'), ('GASTROENTEROLOGIST', 'Gastroenterologist'), ('ONCOLOGIST', 'Oncologist'), ('PULMONOLOGIST', 'Pulmonologist'), ('NEPHROLOGIST', 'Nephrologist'), ('RHEUMATOLOGIST', 'Rheumatologist'), ('ANESTHESIOLOGIST', 'Anesthesiologist'), ('RADIOLOGIST', 'Radiologist'), ('PATHOLOGIST', 'Pathologist')], help_text='Type of doctor (Doctors only)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('LESS_5', '<5 years'), ('5_10', '5-10 years'), ('MORE_10', '10+ years')], help_text='Years of experience (Doctors only)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.TextField(blank=True, help_text='Detailed specialization (Doctors only)', null=True),
        ),
    ]
