# Generated by Django 6.0.1 on 2026-01-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_staff_doctor_type_staff_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='specialization',
        ),
    ]
