# Generated by Django 6.0.1 on 2026-01-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_staff_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uniqueness',
            field=models.CharField(blank=True, help_text='Unique mark or identification on the patient', max_length=100, null=True),
        ),
    ]
