# Generated by Django 6.0.1 on 2026-01-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_patient_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
